services:
  # 1. PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis for Celery Queue
  redis:
    image: redis:6.2-alpine
    container_name: redis_queue
    ports:
      - "6379:6379"

  # 3. MinIO File Storage
  minio:
    image: minio/minio
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data

  # 4. FastAPI API Gateway
  api:
    build: .
    container_name: fastapi_api
    command: /start-api.sh
    ports:
      - "3000:3000"
    volumes:
      - ./app:/code/app  # Mounts your local 'app' folder into the container
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - minio


  # 5. Celery Worker
  worker:
    build: .
    container_name: celery_worker
    # VVVV FINAL CORRECTED COMMAND VVVV
    command: /wait-for-it.sh minio_storage celery -A app.main.celery_app worker --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
